apiVersion: v2
appVersion: 3.3.0
description: 'Helm chart to deploy Free5GC services on Kubernetes.

  '
home: https://dev.gradiant.org/
sources:
- http://free5gc.org
icon: https://free5gc.org/assets/logo.png
maintainers:
- email: lyhcc_email@163.com
  name: lyhcc
name: free5gc
version: 0.1.0
annotations:
  artifacthub.io/category: networking
dependencies:
- name: common
  repository: file://../common
  tags:
  - bitnami-common
  version: 1.x.x
- name: mongodb
  version: ~12.1.19
  repository: file://../mongodb
  condition: mongodb.enabled
- name: free5gc-ausf
  version: ~0.1.0
  repository: file://../free5gc-ausf
  condition: ausf.enabled
  alias: ausf
- name: free5gc-chf
  version: ~0.1.0
  repository: file://../free5gc-chf
  condition: chf.enabled
  alias: chf
- name: free5gc-nrf
  version: ~0.1.0
  repository: file://../free5gc-nrf
  condition: nrf.enabled
  alias: nrf
- name: free5gc-nssf
  version: ~0.1.0
  repository: file://../free5gc-nssf
  condition: nssf.enabled
  alias: nssf
- name: free5gc-udm
  version: ~0.1.0
  repository: file://../free5gc-udm
  condition: udm.enabled
  alias: udm
- name: free5gc-udr
  version: ~0.1.0
  repository: file://../free5gc-udr
  condition: udr.enabled
  alias: udr
- name: free5gc-webui
  version: ~0.1.0
  repository: file://../free5gc-webui
  condition: webui.enabled
  alias: webui